# Generated by Django 3.0 on 2023-09-07 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=100)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(blank=True, choices=[('0', 'Carpenter'), ('1', 'Plumber'), ('2', 'Electrician')], default='Carpenter', max_length=8)),
                ('tflatno', models.CharField(max_length=100)),
                ('tmobile', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('0', 'Service Completed'), ('1', 'On Progress'), ('2', 'Declined')], default='On Progress', max_length=8)),
                ('service_providername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices.Services')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
