# Generated by Django 3.0 on 2023-09-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0002_auto_20230907_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
