# Generated by Django 3.0 on 2023-09-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0003_servicerequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_providername',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_provideruid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tmobile',
            field=models.IntegerField(),
        ),
    ]
