# Generated by Django 3.0 on 2023-09-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0004_auto_20230908_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('0', 'Service Completed'), ('1', 'On Progress'), ('2', 'Accepted'), ('3', 'Declined')], default='On Progress', max_length=8),
        ),
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.CharField(blank=True, choices=[('0', 'Carpenter'), ('1', 'Plumber'), ('2', 'Electrician')], max_length=100),
        ),
    ]
