# Generated by Django 3.0 on 2023-09-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0005_auto_20230908_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.BooleanField(default=False)),
                ('satisfaction', models.CharField(blank=True, choices=[('0', 'Excelent'), ('1', 'Good'), ('2', 'Bad')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='feedback',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HomeServices.feedback'),
        ),
    ]
