# Generated by Django 3.0 on 2023-09-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0006_auto_20230908_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='feedback',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='feedback_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
