# Generated by Django 3.0 on 2023-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0007_auto_20230908_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='provider_uid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
