# Generated by Django 3.0 on 2023-09-08 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0008_feedback_provider_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='uid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
