# Generated by Django 3.0 on 2023-09-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0009_feedback_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='service',
            field=models.ManyToManyField(to='HomeServices.ServiceRequest'),
        ),
    ]
