# Generated by Django 3.0 on 2023-09-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0010_feedback_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='service',
        ),
        migrations.AddField(
            model_name='feedback',
            name='service_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
