# Generated by Django 3.0 on 2023-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0011_auto_20230909_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='uid',
        ),
        migrations.AddField(
            model_name='feedback',
            name='tid',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
