# Generated by Django 3.0 on 2023-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0012_auto_20230909_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='provider_conf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tenant_conf',
            field=models.BooleanField(default=False),
        ),
    ]
