# Generated by Django 3.0 on 2023-09-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0013_auto_20230909_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='provider_conf',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tenant_conf',
            field=models.BooleanField(default=None),
        ),
    ]
