# Generated by Django 3.0 on 2023-09-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0014_auto_20230909_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='provider_conf',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='tenant_conf',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
