# Generated by Django 3.0 on 2023-09-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0015_auto_20230909_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('0', 'Carpenter'), ('1', 'Plumber'), ('2', 'Electrician')], max_length=100)),
                ('srid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices.ServiceRequest')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
