# Generated by Django 3.0 on 2023-09-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0018_auto_20230911_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appointement_dates',
            field=models.ManyToManyField(to='HomeServices.Date'),
        ),
    ]
